# Generated by Django 4.2.7 on 2023-12-20 23:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='rutina',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
